# Generated by Django 5.2.14 on 2026-05-16 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('agm', 'Annual general meeting'), ('training', 'Training / workshop'), ('welfare', 'Welfare event'), ('social', 'Social'), ('other', 'Other')], default='meeting', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/')),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-starts_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rsvp', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('rsvp_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.event')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Officer who recorded attendance (null if self-RSVP).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member')),
            ],
            options={
                'ordering': ('-rsvp_at',),
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventAttendance', to='members.member'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_public', 'starts_at'], name='events_even_is_publ_8a4445_idx'),
        ),
    ]
