# Generated by Django 5.2.14 on 2026-05-16 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'membership counter',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('tsc_number', models.CharField(help_text='Teachers Service Commission number.', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('sub_county', models.CharField(blank=True, choices=[('changamwe', 'Changamwe'), ('jomvu', 'Jomvu'), ('kisauni', 'Kisauni'), ('nyali', 'Nyali'), ('likoni', 'Likoni'), ('mvita', 'Mvita')], max_length=20)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('is_active', models.BooleanField(default=True, help_text='Paid-up / in good standing. Deactivate rather than delete.')),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Optional login account. A member may exist without one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['is_active', 'sub_county'], name='members_mem_is_acti_5e5c0c_idx'), models.Index(fields=['school'], name='members_mem_school_2d7c6c_idx')],
            },
        ),
    ]
