# Generated by Django 5.2.14 on 2026-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline shown at the top of the notice modal.', max_length=160)),
                ('body', models.TextField(help_text='Short message. Plain text; keep it brief and factual.')),
                ('poster', models.ImageField(blank=True, help_text='Optional campaign poster image (client-supplied).', null=True, upload_to='election_notices/')),
                ('learn_more_url', models.URLField(blank=True, help_text="Optional external link (e.g. the campaign's own channel). Campaign material should live there, not here.")),
                ('learn_more_label', models.CharField(blank=True, default='Learn more', max_length=60)),
                ('is_active', models.BooleanField(default=False, help_text='Master switch. Turn OFF at officialisation to make this a neutral branch system with one click.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'election notice',
                'verbose_name_plural': 'election notices',
                'ordering': ('-updated_at',),
            },
        ),
    ]
