# Generated by Django 5.2.14 on 2026-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionnotice',
            name='campaign_portrait',
            field=models.ImageField(blank=True, help_text='Optional candidate portrait shown alongside the body text in the modal. Different visual role from poster.', null=True, upload_to='election_notices/'),
        ),
        migrations.AddField(
            model_name='electionnotice',
            name='campaign_portrait_caption',
            field=models.CharField(blank=True, help_text='Short caption under the portrait (e.g. name and candidacy). Only shown if the portrait is set.', max_length=160),
        ),
        migrations.AddField(
            model_name='electionnotice',
            name='election_date',
            field=models.DateField(blank=True, help_text='Date of the branch election. Drives the countdown widget on the public home page. Leave blank to hide the countdown entirely.', null=True),
        ),
    ]
