# Generated by Django 5.2.14 on 2026-05-16 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('budget_kes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('beneficiaries', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True, help_text='Visible on the public transparency site.')),
            ],
            options={
                'ordering': ('-started_on', 'name'),
                'indexes': [models.Index(fields=['status', 'is_public'], name='projects_pr_status_bd26eb_idx')],
            },
        ),
    ]
