# Generated by Django 5.2.14 on 2026-05-16 03:11

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('admin', 'System administrator'), ('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice chairperson'), ('executive_secretary', 'Executive secretary'), ('assistant_executive_secretary', 'Assistant executive secretary'), ('treasurer', 'Treasurer'), ('assistant_treasurer', 'Assistant treasurer'), ('organizing_secretary', 'Organizing secretary'), ('secretary_secondary', 'Secretary, secondary sector'), ('secretary_tertiary', 'Secretary, tertiary sector'), ('secretary_junior_school', 'Secretary, junior school sector'), ('secretary_gender', 'Secretary, gender affairs'), ('gender_assistant_1st', '1st gender assistant'), ('gender_plwds_2nd', '2nd gender assistant (PLWDs)'), ('gender_youth_3rd', '3rd gender assistant (Youth)'), ('member', 'Ordinary member')], db_index=True, default='member', max_length=40)),
                ('discipline_committee_member', models.BooleanField(default=False)),
                ('welfare_officer', models.BooleanField(default=False)),
                ('manifesto_editor', models.BooleanField(default=False)),
                ('is_2fa_enrolled', models.BooleanField(default=False)),
                ('last_strong_auth_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('email',),
                'indexes': [models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
