# Generated by Django 5.2.14 on 2026-05-17 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_public', 'status'], name='communicati_is_publ_d35090_idx'),
        ),
    ]
