# Generated by Django 5.2.14 on 2026-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_announcement_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image shown above the body on the public news page. Use for instructional graphics, event posters, etc.', null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Accessibility description of the image. Leave blank for decorative images; fill in for informative ones (e.g. a step-by-step guide should describe what it shows).', max_length=200),
        ),
    ]
