# Generated by Django 5.2.14 on 2026-05-16 17:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0002_expense_project'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareClaim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('bereavement', 'Bereavement'), ('illness', 'Illness / hospitalisation'), ('accident', 'Accident'), ('education', 'Education support'), ('other', 'Other')], max_length=12)),
                ('amount_requested_kes', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('withdrawn', 'Withdrawn by claimant')], default='submitted', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welfare_claims', to='members.member')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welfare_claim', to='finances.expense')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_welfare_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='welfare_wel_status_89d531_idx'), models.Index(fields=['claimant', 'status'], name='welfare_wel_claiman_0d5dd6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_requested_kes__gt', 0)), name='welfare_amount_positive')],
            },
        ),
    ]
