# Generated by Django 5.2.14 on 2026-05-16 22:52

import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=16, unique=True)),
                ('category', models.CharField(choices=[('misconduct', 'Professional misconduct'), ('financial', 'Financial impropriety'), ('ethics', 'Ethics / code of conduct'), ('grievance', 'Grievance'), ('other', 'Other')], max_length=12)),
                ('summary', django_cryptography.fields.encrypt(models.TextField())),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('under_investigation', 'Under investigation'), ('hearing', 'Hearing scheduled'), ('decided', 'Decided'), ('appealed', 'Under appeal'), ('closed', 'Closed')], default='opened', max_length=20)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed (no case)'), ('warning', 'Warning issued'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('other_sanction', 'Other sanction')], default='pending', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cases', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_cases', to='members.member')),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('note', 'Investigation note'), ('evidence', 'Evidence logged'), ('hearing_minute', 'Hearing minute'), ('decision', 'Decision record'), ('appeal', 'Appeal record')], max_length=16)),
                ('notes', django_cryptography.fields.encrypt(models.TextField())),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='discipline.disciplinarycase')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['status'], name='discipline__status_bdfd12_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['subject', 'status'], name='discipline__subject_259dfd_idx'),
        ),
    ]
