# Generated by Django 5.2.14 on 2026-05-16 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('c2b', 'Paybill C2B'), ('stk', 'STK push')], max_length=8)),
                ('status', models.CharField(choices=[('received', 'Received, not yet processed'), ('matched', 'Matched to a member'), ('unmatched', 'No member found — needs review'), ('duplicate', 'Duplicate receipt, ignored'), ('failed', 'STK push failed / cancelled')], default='received', max_length=12)),
                ('mpesa_receipt', models.CharField(max_length=32, unique=True)),
                ('account_reference', models.CharField(blank=True, help_text='What the payer typed as the account — expected to be a membership_id for C2B.', max_length=64)),
                ('msisdn', models.CharField(blank=True, help_text='Payer phone, stored masked.', max_length=20)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transaction', to='finances.financialcontribution')),
            ],
            options={
                'ordering': ('-paid_at',),
                'indexes': [models.Index(fields=['status', 'paid_at'], name='mpesa_mpesa_status_3115b1_idx'), models.Index(fields=['account_reference'], name='mpesa_mpesa_account_20654c_idx')],
            },
        ),
    ]
