# Generated by Django 5.2.14 on 2026-05-16 17:17

import apps.reports.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('financial', 'Financial report'), ('agm', 'AGM minutes'), ('audit', 'Audit report'), ('activity', 'Activity report'), ('circular', 'Circular / notice'), ('other', 'Other')], default='other', max_length=12)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='reports/%Y/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), apps.reports.models.validate_report_size])),
                ('is_published', models.BooleanField(default=False, help_text='Published reports are visible to the public.')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-created_at'),
                'indexes': [models.Index(fields=['is_published', 'year'], name='reports_rep_is_publ_1b632f_idx')],
            },
        ),
    ]
